apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: my-demo
  name: my-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-demo
    spec:
      containers:
      - image: t8coredelivery.azurecr.io/demoapp:latest
        name: my-demo
        ports:
        - containerPort: 8080
        resources: {}
status: {}