apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: my-demo
  name: my-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: my-demo
  type: LoadBalancer
status:
  loadBalancer: {}